#!/bin/bash
# Distributed under the terms of the GNU General Public License v2

uid_gid=$1
perms=$2
capset=$3
path=$4

#set file-mode
chmod $perms $path
#remove suid-bit
chmod -s $path

#set owner/group
chown $uid_gid $path

#set the capability
setcap "$capset=ep" "$path" 

#check if the capabilitiy got set correctly
setcap -v "$capset=ep" "$path"
res=$?

#if caps couldn't be set, set suid bit as fallback
if [ $res -ne 0 ]; then
	chmod u+s $path 
fi

exit $res
